### ISSUE TITLE
Images no longer work in latest WP & Civi

### ISSUE THREAD

**Issue by matt-carboncoop** [veda-consulting/uk.co.vedaconsulting.mosaico#292] opened 2019-02-04 16:57 UTC
Hi there,
I upgraded my wordpress and Civi versions to the latest just before xmas and all the images in my previous newsletters were replaced by broken image icons. I figured that as version 1.1 was 'no longer supported' I should move up to the latest beta, so installed the shoreditch, flexmailer and mosaico-beta4, but my images did not return.
Tried with a brand new template. In the interface I no longer have the upload icons (as others have reported) but I can hover over the area to see an icon (slightly hidden under the down arrow) and upload an image. When I do so a thumbnail of the image appears briefly with an image uploading bar, but after about 2 seconds this is replaced by the broken image icon. 
I've tested my imagemagick installation at the commandline and it works as expected, I can also go to the specified path the broken image links to and the image is there. I've tried updating my Mosaico to the latest version on github, but no change. Any ideas how I can fix it?

**Example broken image link from newsletter:**
https://yorkshirecnd.org.uk/civicrm?page=CiviCRM&amp;q=civicrm/mosaico/img&amp;src=https%3A%2F%2Fyorkshirecnd.org.uk%2Fwp-content%2Fplugins%2Ffiles%2Fcivicrm%2Fpersist%2Fcontribute%2Fglobal_ban_fb4f2564604c11f11a53d72276a3f74a.png&amp;method=resize&amp;params=534%2Cnull"

**Accessing the image refered to above directly, is fine, image exists and is viewable:**
https://yorkshirecnd.org.uk/wp-content/plugins/files/civicrm/persist/contribute/global_ban_fb4f2564604c11f11a53d72276a3f74a.png

**Software versions:** 
Wordpress 5.03 / CiviCRM 5.8.2
PHP 7.1.26 / ImageMagick 6.9.4-5 Q16 x86_64
FlexMailer (org.civicrm.flexmailer) version 1.0-beta1
CiviCRM Bootstrap theme (org.civicrm.shoreditch) version 0.1-alpha30
Mosaico (uk.co.vedaconsulting.mosaico) version 2.0-beta4.1544700816

**Comment by mwestergaard** [comment] 2019-02-11 00:24
Same experience on my test site. My production site is working with 2.0-beta3.1512698300.

**Comment by matt-carboncoop** [comment] 2019-02-11 13:05
Thanks for the response @mwestergaard glad to know it's not just me. Perhaps I should give beta3 a try then as upgraded straight from 1.1 where I also had the problem. Writing the issue above was useful in that I noted in clicking on a broken link I get "You do not have permission to access this content". The images are public readable and show fine when viewed directly, so suspect it must be a permissions issue related to mosaico...

**Comment by themak1985** [comment] 2019-02-18 02:05
Hi @matt-carboncoop and @mwestergaard,

Sometimes the issue is with old templates.  I suspect that if you were to recreate your template from from a new versafix-1 - all would work without issue. 

This is likely related to #160 - essentially - when we upgraded to beta 3 (and I believe then again to beta 4, but I could be mistaken), we had to rebuild our templates from scratch. When we did, the issue went away with the new templates. Luckily our templates aren't very complicated. I think this will be fixed in the final and a note about upgrading from previous beta versions will be included via documentation. 

See if creating a new template from base fixes it for you.

**Comment by mwestergaard** [comment] 2019-02-18 18:39
@themak1985 Bingo! That helped! Luckily, I have only two templates and one of them is a slight derivative of the other.

While working of this, I also found a confounding issue that was unrelated to Mosaico itself. I discovered that the main apache configuration file (/etc/apache2/apache2.conf in my case) had changed in a recent upgrade. An "AllowOverride" directive had been reset so my .htaccess settings were ignored in one directory path. That caused image access troubles, even with new templates. Just a coincidence that this occurred around the same time. I started investigating it when I noticed I was getting a 500 error trying to "View in Browser" from a mailing or "Public View" from the admin interface. After resetting the conf file, your suggestion for recreating templates worked.

I should add that I'm at:
WordPress 5.0.3
CiviCRM 5.10.2
Mosaico 2.0-beta4.1544700816
Shoreditch 0.1-alpha30
FlexMailer 1.0-beta1
PHP 7.2.15
ImageMagick 6.9.7-4

**Comment by matt-carboncoop** [comment] 2019-02-27 17:24
@themak1985 No fix for me still, sadly, hosed all my previous templates and just using new ones for some time now in troubleshooting. 
@mwestergaard I also tried Beta3 but I still have the same issue.
I've also searched for rogue spaces in my civicrm-setting.php and in my theme config files as suggested on [stackexchange](https://civicrm.stackexchange.com/questions/19386/mosaico-imagickdraw-unable-to-load-any-image-on-templates/19387#19387) and many of the other suggestions from other issues raised on similar topics - running the latest 5.10.4

I've not been able to send a newsletter for 3 months and have put days into troubleshooting.

**Comment by Dubidubiduu** [comment] 2019-05-31 09:00
Same goes for me. No idea where to search for a solution. I have also changed my php version while upgrading. While I have no clue what this imagick is about, you can change that setting at Admin -> CiviMail -> Mosaico. But for me it doesn't make a change.. 

- Wordpress 5.2.1
- CiviCrm 5.13.4
-  OpenStreetMap Geocoding (de.systopia.osm)	Aktiviert 	1.2.1
-  Fuzion Tokens (nz.co.fuzion.civitoken)	Aktiviert 	1.3
-  API v4 (org.civicrm.api4)	Aktiviert 	4.4.2
-  FlexMailer (org.civicrm.flexmailer)	Aktiviert 	0.2-alpha5
-  CiviCRM Bootstrap theme (org.civicrm.shoreditch)	Aktiviert 	0.1-alpha31
-  SEPA Direct Debit (org.project60.sepa)	Aktiviert 	1.2.5
-  Mosaico (uk.co.vedaconsulting.mosaico)	Aktiviert 	2.0.1556289017
- PHP 7.2

**Comment by mattwire** [comment] 2019-05-31 09:08
@matt-carboncoop @Dubidubiduu Do new templates work ok?  It's just the old ones with broken images?  If so, you'll need to run a find/replace on the templates already stored in the database to update the URLs.

**Comment by matt-carboncoop** [comment] 2019-05-31 09:54
Speaking for me it's the same on the new templates. I've tried multiple php
versions and imagemagik is found. Image pops up momentarily, then is
replaced by a broken link. I can browse to the location and the image is
there.

**Comment by Dubidubiduu** [comment] 2019-05-31 10:23
I tried with new Mails and different templates, doesn't make any difference for me. Deactivated Firewall, Fuzion Tokens and Smarty. No difference yet.

I actually tried to manipulate in the database, but somehow the manipulation of an entry in civicrm_mailing is not persisting. But I guess this is something different.

**Comment by deepak-srivastava** [comment] 2019-05-31 13:31
@matt-carboncoop @Dubidubiduu Could you try this patch and see if it helps - https://github.com/deepak-srivastava/uk.co.vedaconsulting.mosaico/commit/c535f438f05ee450c8798bd692c6add77965c8c0
I've noticed that sometimes in wordpress there are output buffers generated by another plugin or theme, which causes problems and it's not straight forward to find out the source. If it's same problem it might fix it.

**Comment by Dubidubiduu** [comment] 2019-05-31 15:19
Thank you for the effort. It wasn't a solution for me, tho.

BUT I deactivated every Wordpress plugin, and it worked again, activating them step by step and it shows that Search & Filter Pro 2.4.6 is the villain. So I will just deactivate this when I send mass mails

**Comment by christianwach** [comment] 2019-05-31 15:47
> it shows that Search & Filter Pro 2.4.6 is the villain

Would be good to know exactly *why* this plugin is messing with Mosaico. Though being non-free, it's impossible for us to do that. Fancy littering it with `error_log` statements to figure it out? :)

**Comment by Dubidubiduu** [comment] 2019-05-31 22:42
How to do that? Enabled debug mode, don't have anything yet in the debug logs.

Using Firefox, activated webdevelopertoolbar and I still get 200 codes for the images, sometimes they even blink shortly but disappear then..

**Comment by eileenmcnaughton** [comment] 2019-05-31 23:24
So I would actually suggest you set aside a day to read  the docs & get phpstorm debug running. Debugging in phpstorm is a wonderful thing but you need to take the time to work through setting it up & perhaps deal with some gotchas. I think one of the biggest problems people have with getting debugging working is that they are really just wanting to get it sorted quickly so they can solve their other problem. However, this is GSOC. You don't have a customer being billed by the hour so take the time to take a step back & download phpstorm & work through their docs. I would create a psalm project & try to debug that directly if you can. Assuming this is late in the day / evening for you I'd leave it for a fresh new day

You should probably also apply for the free for students option https://www.jetbrains.com/student/ - if it runs out in 30 days we'll figure something out to keep you going on it.

**Comment by eileenmcnaughton** [comment] 2019-05-31 23:25
sorry - ignore comment - I thought if was from a diff thread

**Comment by matt-carboncoop** [comment] 2019-06-17 13:04
@deepak-srivastava I've just added your code and immediately the striped image box showing the image dimensions on the block template returned, which is great. When adding an image with GD graphics selected it pops up for a couple of seconds and then disappears with an "Unexpected Upload Error (Internal Server Error)" popup. But I've just enabled image magick again to try with the new code added and IT WORKS!!!!! 
I can't thank you enough, now we have a proper newsletter again!

**Comment by deepak-srivastava** [comment] 2019-06-17 16:38
@matt-carboncoop i'm glad it helped :) May be at some point we can get a generalized solution in the extension.

**Comment by andersiversen** [comment] 2019-09-09 15:07
@deepak-srivastava this patch solves one of the longest standing issues for me (#186 ) - thank you! We have been unable to use the Mosaico extension for years, but I guess we'll start using it now :)
And by the way we're on Drupal 7.67, CiviCRM 5.13.4, php 7.1. So not only a WP problem.

**Comment by hsjdc** [comment] 2019-11-08 05:16
I think I'm having a related issue? Not sure, as I'm entirely new to Mosaico, but it's exactly what we need, I think.

In any case, Flexmailer and Mosaico extensions both installed through CiviCRM admin, Imagick is good to go, and the DS patch has been applied. I can get to the Mosaico templates and open one for editing, but uploading images always -- as described here -- results in a fleeting preview followed by an "Internal Server Error" message.

CiviCRM: 5.19
WordPress: 5.2.4
Mosaico: 2.3.1572289217 
FlexMailer: 1.1.0
PHP: 7.1
![Screenshot from 2019-11-08 11-56-58](https://user-images.githubusercontent.com/27632111/68451250-929a0d80-0220-11ea-888e-09d6011bc86b.png)

I can also confirm that the images are actually uploading, to public_html > wp-content > uploads > civicrm > persist > contribute > images > uploads

**Comment by dandrzejewski** [comment] 2020-02-23 23:54
> 
> 
> I think I'm having a related issue? Not sure, as I'm entirely new to Mosaico, but it's exactly what we need, I think.
> 
> In any case, Flexmailer and Mosaico extensions both installed through CiviCRM admin, Imagick is good to go, and the DS patch has been applied. I can get to the Mosaico templates and open one for editing, but uploading images always -- as described here -- results in a fleeting preview followed by an "Internal Server Error" message.
> 
> CiviCRM: 5.19
> WordPress: 5.2.4
> Mosaico: 2.3.1572289217
> FlexMailer: 1.1.0
> PHP: 7.1
> ![Screenshot from 2019-11-08 11-56-58](https://user-images.githubusercontent.com/27632111/68451250-929a0d80-0220-11ea-888e-09d6011bc86b.png)
> 
> I can also confirm that the images are actually uploading, to public_html > wp-content > uploads > civicrm > persist > contribute > images > uploads

I think this is a different issue. Make sure you have ImageMagick installed along with the PHP ImageMagick extension.

**Comment by mwestergaard** [comment] 2020-03-12 22:32
See also https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/365#issuecomment-598455472

**Comment by dandrzejewski** [comment] 2020-04-19 21:49
So what solved this is in fact adding the stuff from the code change mentioned above:

```
      // DS: clean any output buffers
      $levels = ob_get_level();
      for ($i=0; $i<$levels; $i++) {
        ob_end_clean();
      }
```

**Comment by marcusjwilson** [comment] 2020-04-30 14:04
> 
> 
> @matt-carboncoop @Dubidubiduu Could you try this patch and see if it helps - [deepak-srivastava@c535f43](https://github.com/deepak-srivastava/uk.co.vedaconsulting.mosaico/commit/c535f438f05ee450c8798bd692c6add77965c8c0)
> I've noticed that sometimes in wordpress there are output buffers generated by another plugin or theme, which causes problems and it's not straight forward to find out the source. If it's same problem it might fix it.

Wow.  Searched for ever to find a resolution to this.  Looks like a WordPress Popup plugin we installed recently must have added some output buffering.  Deepak's solution strips it back.  Worth adding this to core?

**Comment by mattwire** [comment] 2020-05-01 12:15
@deepak-srivastava Can you create a PR for https://github.com/deepak-srivastava/uk.co.vedaconsulting.mosaico/commit/c535f438f05ee450c8798bd692c6add77965c8c0

**Comment by mattwire** [comment] 2021-01-07 18:54
Closing following 2.6 release. Please reopen if still an issue

**Closed as completed by mattwire** 2021-01-07 18:54 UTC

**Comment by mcollopy** [comment] 2021-03-22 07:57
Yes I'm getting the issue in 2.6, Civi 5.35.1
- Wordpress, php 7.3
- all other plugins disabled
- all troubleshooting steps followed:  permalinks, clean URLs, reset paths, base page 'civicrm'

Note I was able to get Mosaico working on the same server with a fresh installation of Civi with Wordpress
- same versions of everything, so I know the underlying software is OK
- the issue has to either be with paths, old files, or the database records

Troublehooting Database
- when I try the test codebase with the problem database - it works!
- the 'gallery' showed only the files in the test codebase folder location, but drag and drop worked
- when I copy the problem codebase and copied wordpress and civicrm database, I can replicate the problem
- problem then persists if I change to civicrm test database
- then, problem codebase with test wordpress database, ir works again
- finally, problem codebase, test wordpress and problem civicrm - it still works
- conclusion - wordpress is the problem

What records might there be in Wordpress that could cause an issue?

Thanks

**Comment by mcollopy** [comment] 2021-03-22 21:05
OK I've narrowed it down to permalinks
- this worked /index.php/%year%/%monthnum%/%day%/%postname%/
- this didn't /%postname%/
- so then I tried this ands it works  /index.php/%postname%/

The issue is something to do with index.php being required in the path.
Is this something to do with .htaccess?
I also notice there is a wp_options record 'rewrite_rules' which could also be the issue - see attached

[rerwite_rules.txt](https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/files/6185271/rerwite_rules.txt)

**Comment by mattwire** [comment] 2021-03-22 21:57
@mcollopy Did you try opening permalinks page in wordpress and saving? That can flush/reset them and sometimes solves this kind of thing.

**Comment by mcollopy** [comment] 2021-03-22 22:44
RESOLVED the issue was the Apache2 config to allow the permalinks to work.

Yes @mattwire  I had done that and the other steps mentioned, however I noticed that the page 'CiviCRM' was not viewable at the URL /civicrm so suspected an apache2 configuration issue.

See this post https://wordpress.stackexchange.com/a/167148
"In terminal type:
sudo gedit /etc/apache2/apache2.conf
Find:
<Directory /var/www/>
And make sure the AllowOverride directive is set to All."

This worked as above and also if the directive was just put into the vhost rather than apache2.conf
Can anyone see any issues leaving this setting in apache2.conf?  Any risks?

Thanks
