### ISSUE TITLE
Minor CSS issue - help icons are blue squares

### ISSUE THREAD

**Issue by JKingsnorth** [veda-consulting/uk.co.vedaconsulting.mosaico#178] opened 2017-08-03 13:51 UTC
![image](https://user-images.githubusercontent.com/5212601/28924809-da38fec8-785a-11e7-9ce3-cdf055f2e48c.png)

#bootstrap-theme a.helpicon {
    background-color: #42afcb;
}
Here?
https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/a2316a634ebee0b37878e89a3f3374c524795e76/sass/civicrm-override/_form.scss#L115

**Comment by totten** [comment] 2017-11-22 20:17
@JKingsnorth, I used to have this problem, too, but I haven't been able to replicate it in a while.

I retested with every permutation of these variables:
 * Set the CiviCRM CSS URL to (a) default or (b) Shoreditch
 * Have the Internet connection (a) online or (b) offline. (Some quirks in the past depended on loading remote resources.)

In each case, the icon appeared correct in Firefox. I did reset caches (`cv flush`) and force-reload the browser (eg Ctrl-Shirt-R in Firefox).

Closing because it can't be reproduced -- I suspect this has been resolved. If you still have the problem, go ahead and reopen.

(Note: Tested with latest revisions of 4.7 and Shoreditch.)

**Closed as completed by totten** 2017-11-22 20:17 UTC
Labels: 2.x
