### ISSUE TITLE
Social media icons are not visible while previewing the template

### ISSUE THREAD

**Issue by meladawy** [veda-consulting/uk.co.vedaconsulting.mosaico#139] opened 2017-04-24 14:22 UTC
**PROBLEM**
Social media icons are visible while building the template but links are getting broken when "Test" => "Preview the template"

![mosaico](https://cloud.githubusercontent.com/assets/2423218/25341483/3aba9410-2909-11e7-91b0-cf4db7d0af5e.gif)

**Guessing**
I believe its more related to [Mosaico library ](https://github.com/voidlabs/mosaico) and the way [versafix template](https://github.com/voidlabs/mosaico/blob/master/templates/versafix-1/template-versafix-1.html#L1398) is called from Mosaico CiviCRM extension

https://github.com/voidlabs/mosaico/blob/master/templates/versafix-1/template-versafix-1.html#L1398

I believe calling template-versafix-1.html somehow from iframe instead of using modal should resolve this.

**Comment by jmcclelland** [comment] 2017-07-12 13:51
I think this is a duplicate of https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/160

**Comment by mattwire** [comment] 2017-08-23 14:41
See PR #182 for social icons fix

**Comment by totten** [comment] 2017-11-29 05:17
The visualization above is a beautiful report of the problem.

I'm closing this because #160 seems to have slightly more discussion.

**Closed as completed by totten** 2017-11-29 05:17 UTC
Labels: topic:hyperlinking
