### ISSUE TITLE
Image path issues - Social media icons are not always visible

### ISSUE THREAD

**Issue by mattwire** [veda-consulting/uk.co.vedaconsulting.mosaico#160] opened 2017-05-27 08:53 UTC
Having a few issues with image paths.  Running latest version on Drupal with civicrm 4.7.19.

1. Social icons don't display in preview as it is looking for a path relative to the site root (ie. https://sitename.org/templates/versafix-1/img/social_def/facebook_ok.png).
**Workaround:** Create a symlink in the site root:
`templates -> sites/default/files/civicrm/ext/uk.co.vedaconsulting.mosaico/packages/mosaico/templates`

2. Social icons don't display in mailing public URL (eg. https://sitename.org/civicrm/mailing/view?id=125) as it is looking for a path relative to civicrm (which won't work!) (ie. https://sitename.org/civicrm/mailing/templates/versafix-1/img/social_def/facebook_ok.png)

**Comment by freedomlives** [comment] 2017-06-06 11:48
Same here-- the social icons don't work in the email or on the public mailing view.

**Comment by JKingsnorth** [comment] 2017-08-03 13:28
The social icons don't display in the preview because the block definition uses relative URLs:
https://github.com/civicrm/mosaico/blob/b2b271fe6f23c3393e1196a10fa9368329e5bb46/templates/versafix-1/template-versafix-1.html#L1402

The relative URLs are rewritten to absolute URLs when the mailing is actually sent though:
https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/bc9d18cadf0984b427f533378451996b93229939/CRM/Mosaico/UrlFilter.php#L34

**Comment by mattwire** [comment] 2017-08-23 14:41
See PR #182 for social icons fix

**Comment by totten** [comment] 2017-11-29 05:19
As noted in the PR, I've been [unable to reproduce the problem](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/pull/182#issuecomment-347683815). Can anyone say if they still have the problem -- or if there's an important difference in environment/settings?

**Comment by mattwire** [comment] 2017-11-29 18:51
@totten Give me a couple of days and I'll do some testing

**Comment by mattwire** [comment] 2017-12-02 12:45
@totten I've just tested with the latest HEAD on 2.x and I'm still seeing images fail at the first hurdle:
New mailing->Edit->Add social media block->Preview->As HTML->Social icons not shown:
![civicrm-demo mjwconsult co uk_civicrm_a_](https://user-images.githubusercontent.com/2052161/33515672-77f7100c-d75e-11e7-8fb4-845031f68f87.png)

CiviCRM 4.7.27, shoreditch:master, mosaico:2.x flexmailer:master.

**Comment by agileware-fj** [comment] 2018-01-18 04:57
For what it's worth, we *were* seeing this problem a while back, but with mosaico 2.x branch, social icons are now displaying correctly and have absolute URLs in each of the 4 scenarios.

The entry in the civicrm_mailing table actually has the absolute URL to the social icon / any uploaded image, so it **seems** this is done client side.

For reference, I've been testing on CiviCRM 4.7.29 on Drupal 7.

**Comment by jmcclelland** [comment] 2018-01-22 19:18
It is now working for me too.
I think I see why this problem may be so hard to reproduce.
When I choose the default versifix-1 template, the social media icons work as expected in both the preview and in the delivered email.
However, when I sent via a template that is based on versifix-1 that was made in a prior version,  the links were in the form:
https://ptp.ourpowerbase.net/templates/versafix-1/img/social_def/twitter_ok.png

Instead of:
https://ptp.ourpowerbase.net/sites/all/extensions/uk.co.vedaconsulting.mosaico/packages/mosaico/templates/versafix-1/img/social_def/twitter_ok.png

I tried deleting and re-creating the social icons block in the bad template and got the same result.

When I trashed my existing template and rebuilt it, the icons started working properly.

**Comment by jaapjansma** [comment] 2018-01-23 14:15
I have updated the mosaico extension from 2.0-beta2 to 2.0-beta3. I have also migrated the templates. I discovered that with the old templates the social icons are still broken but when I use a new template the social icons are fixed.

**Comment by MarshCastle** [comment] 2018-01-23 14:47
Is there any chance of this being fixed on v1.0?
v2.0 seems a long way off being "Stable" (with the two dependancies being stable too) - so I'm after something that has a bit more of a guarantee on it for use on sites with sensitive data.

**Comment by jmcclelland** [comment] 2018-01-23 22:13
My experience (which is confirmed by the last few posts) is that this issue is fixed and should be closed.

Since the release is still beta, I don't think it's worth the effort to try to fix templates that were made in previous versions.

I think it's acceptable to tell people: If you are experiencing this bug and you are using a template made with a previous version, delete your template and re-create it from scratch.

**Comment by totten** [comment] 2018-01-25 00:36
Thanks @jmcclelland @jaapjansma. I really like how this explanation is able to address the different experiences ("works for me", "doesn't work for me"). :+1: 

It'd be great if one of the earlier participants here (like @mattwire) could re-test. Absent contradictory info, I'm also inclined to close.

**Comment by mattwire** [comment] 2018-02-16 19:00
@totten I've now had the opportunity to upgrade two sites from my version of the mosaico extension to the latest master (beta4).  I'm pleased to say that on new templates there are no image path issues, and I can "fix" the old templates by editing them directly in the database to ensure they all have full rather than relative URLs.

So, if we can add a note to the README or something that image path issues are caused by templates created with an older beta version and they should delete/recreate them then I think we can close this.

**Comment by totten** [comment] 2018-02-16 20:14
Woot! @mattwire 

We could potentially kick the can down to the 2.0-final release announcement.

IMHO, the `README.md` is due for a reorg -- e.g. I think the main README should basically be:
 * A screenshot
 * A brief, 1-2 sentence description
 * A bulleted list of sub-documents ("Introduction", "Installation", "Development"). 
     * Notes about social-media icons and upgrades could go in a page for "Troubleshooting" or "Upgrading"?

**Closed as completed** 2019-10-11 13:38 UTC
Labels: topic:hyperlinking
