### ISSUE TITLE
"Sorry an error occurred and your information was not saved" when trying to save template or send mail

### ISSUE THREAD

**Issue by josh-ecocentre** [veda-consulting/uk.co.vedaconsulting.mosaico#295] opened 2019-02-25 04:20 UTC
I'm getting the above issue when I either: 
1) try to create a new template using Mosaico's templates, or 
2) try to send a mail (or test email) through CiviMail while building off a Mosaico template, or
3) trying to save a draft mail

I've checked to make sure that: 
- The permission to Grant IDS Skip has been applied
- The permissions to edit message templates, edit system workflow message templates, and edit user-driven message templates, have all been granted

When I create the new template, it gives this error message whether I use the Versafix template, the tutorial template, or the tedc15 template.

Nothing appears in my CiviCRM error log. 

Running the following: 
- Drupal 7.65
- CiviCRM 5.10.4
- Mosaico 2.0.1556289017
- Flexmailer 1.0-beta1
- CiviCRM Bootstrap Theme (Shoreditch) 0.1-alpha30

I installed these in the order: 1) Shoreditch, 2) Flexmailer, 3) Mosaico.

Any idea on what I can do? Cheers.

**Comment by lunarstack1** [comment] 2019-04-16 05:48
+1.

**Comment by lunarstack1** [comment] 2019-04-16 06:23
After debugging, I found this was related to Wordfence blocking some of the web server requests from the plugin. Adding new exceptions fixed the issue.

**Comment by josh-ecocentre** [comment] 2019-04-16 23:31
> After debugging, I found this was related to Wordfence blocking some of the web server requests from the plugin. Adding new exceptions fixed the issue.

Hey Adam,

Thanks for your reply! Sorry I'm not well versed in how any of this works... do you have any resources that could walk me through how to fix this on my end?

EDIT: Ah wait never mind, Wordfence is for Wordpress, whereas I'm using Drupal, so that fix wouldn't work for me.

**Comment by josh-ecocentre** [comment] 2019-05-17 01:09
Hi all,

Just upgraded to Mosaico 2.0.1556289017 and still having this error.

These are my Mosaico settings on CiviCRM for reference.

CivCRM 5.10.4
Drupal 7.65

![image](https://user-images.githubusercontent.com/47312876/57896302-7cc01700-7893-11e9-98f2-b23cac5f9d97.png)

@deepak-srivastava  @mattwire

**Comment by aydun** [comment] 2019-05-17 12:22
@josh-ecocentre I also had this problem.  In my case, the problem was that mailing was disabled (/civicrm/admin/setting/smtp).  It makes sense that test mails fail if mailing is not enabled, but the error message should be more informative about the cause of failure rather than being generic and misleading.

Have in look in Drupal's /admin/reports/dblog for clues.

**Comment by josh-ecocentre** [comment] 2019-05-19 22:36
@aydun thanks for your reply! Just checked, my mailing is enabled. I can save and send emails as normal through CiviMail but not when Mosaico is enabled.

Cheers,

**Comment by josh-ecocentre** [comment] 2019-07-05 06:49
@deepak-srivastava @mattwire any idea on what I could do here to fix this?

**Comment by mattwire** [comment] 2021-01-07 18:52
Closing following 2.6 release. Please reopen if still an issue

**Closed as completed by mattwire** 2021-01-07 18:52 UTC
