### ISSUE TITLE
Unexpected upload error (SyntaxError: Unexpected token < in JSON at position 0)

### ISSUE THREAD

**Issue by jmcheung** [veda-consulting/uk.co.vedaconsulting.mosaico#53] opened 2016-10-14 15:52 UTC
We get this error using the extension. It occurs when you upload an image to the template.

Is there a quick fix, have we done something wrong?

**Comment by rocxa** [comment] 2016-10-14 15:54
This is usually caused by the image folders 'uploads' 'uploads/images'
'uploads/images/static' 'uploads/images/thumbnails' on the server not
existing or not being writable.

**Comment by jmcheung** [comment] 2016-10-14 15:58
hi @rocxa that was quick!

We have 'public_html/sites/default/files/civicrm/persist/contribute/images' in our Drupal/CiviCRM site

Does it need these additional directories in there?

**Comment by rocxa** [comment] 2016-10-14 16:03
Yes, that sounds like the right place for a standard CiviCRM.

You probably just need the images/static and images/thumbnails directories
creating. We have added the 'uploads' level directory to our site.

The extension should create these directories, I haven't looked into why it
doesn't sometimes.

**Comment by deepak-srivastava** [comment] 2016-10-14 16:09
Yep extension should be creating those directories. 
Is it an old install and you upgraded? If yes might want to re-install. Or otherwise we need to look into where its failing.

I think we should add all dir checks anyway with the runcheck - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/master/CRM/Mosaico/Page/Index.php#L28

**Comment by jmcheung** [comment] 2016-10-14 18:05
I created these directories manually and still no good: -
sites/default/files/civicrm/persist/contribute/images/static
sites/default/files/civicrm/persist/contribute/images/thumbnails

should they be 755 permissions?

**Comment by rocxa** [comment] 2016-10-14 19:31
Do you have any watchdog/civilog errors showing you where mosaico is trying
to upload the images? It sounds like it isnt the directory it appears to
be.

I have created a PR that moves the directory mosaico uses for images to the
same one civimail image browser uses. You might want to try that.

**Comment by rocxa** [comment] 2016-10-14 19:38
#54

**Comment by rocxa** [comment] 2016-10-26 22:00
#57 (waiting for testing/merge)
New PR auto creates the directories (amongst other things) so may help with this issue as well.

**Comment by totten** [comment] 2017-11-14 20:12
The first PR mentioned (54) is merged, and the second PR was resubmitted and then merged (65).

**Closed by totten** 2017-11-14 20:12 UTC
Labels: enhancement
