### ISSUE TITLE
Sending 'test' and Saving are not having any outcomes

### ISSUE THREAD

**Issue by petednz** [veda-consulting/uk.co.vedaconsulting.mosaico#35] opened 2016-09-07 16:55 UTC
Hi - installed alpha-7. Created a template. Tried 'send test' and got a message saying "test email sent" but nothing is received.
I then saved, and get message saying "Saving in .." and then "Saved as ..." but at civicrm/admin/messageTemplates?reset=1 on the Mosaico tab i see nothing, and when i look in the db in civicrm_mosaico_msg_template i see no rows of data.

Recent error logs show

LOCATION	.../civicrm/mosaico/dl
REFERRER	.../civicrm/mosaico/editor?snippet=2
MESSAGE	Warning: implode(): Invalid arguments passed in CRM_Core_IDS->kick() (line 257 of /srv/www/nzsq/my.nzsq.org.nz/sites/all/modules/civicrm/CRM/Core/IDS.php).

and

MESSAGE	Notice: Undefined variable: args in CRM_Core_IDS->kick() (line 257 of /srv/www/nzsq/my.nzsq.org.nz/sites/all/modules/civicrm/CRM/Core/IDS.php).

**Comment by petednz** [comment] 2016-09-07 17:00
Just spotted that if i go back to /civicrm/mosaico/index?reset=1 I see "YOU have saved content in this browser", and if I click on 'show' I see the two templates listed that I have created and tried saving. But no sign of them in civi

**Comment by xurizaemon** [comment] 2016-09-07 21:44
Watching logfiles on this, saw an IDS error when attempting to save Mosaico template.

    ==> sites/default/files/civicrm/ConfigAndLog/CiviCRM.896afcf299887bd1183a53bcb41f7e62.log <==
    Sep 08 09:41:14  [info] $Fatal Error Details = Array
    (
        [message] => There is a validation error with your HTML input. Your activity is a bit suspicious, hence aborting
        [code] =>
    )


    Sep 08 09:41:14  [info] $backTrace = #0 /srv/www/example/my.example.org/sites/all/modules/civicrm/CRM/Core/Error.php(364): CRM_Core_Error::backtrace("backTrace", TRUE)
    #1 /srv/www/example/my.example.org/sites/all/modules/civicrm/CRM/Core/IDS.php(275): CRM_Core_Error::fatal("There is a validation error with your HTML input. Your activity is a bit susp...")
    #2 /srv/www/example/my.example.org/sites/all/modules/civicrm/CRM/Core/IDS.php(190): CRM_Core_IDS->kick(Object(IDS_Report))
    #3 /srv/www/example/my.example.org/sites/all/modules/civicrm/CRM/Core/IDS.php(92): CRM_Core_IDS->react(Object(IDS_Report))
    #4 /srv/www/example/my.example.org/sites/all/modules/civicrm/CRM/Core/Invoke.php(139): CRM_Core_IDS->check((Array:3))
    #5 /srv/www/example/my.example.org/sites/all/modules/civicrm/CRM/Core/Invoke.php(83): CRM_Core_Invoke::init((Array:3))
    #6 /srv/www/example/my.example.org/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
    #7 /srv/www/example/my.example.org/sites/all/modules/civicrm/drupal/civicrm.module(489): CRM_Core_Invoke::invoke((Array:3))
    #8 [internal function](): civicrm_invoke("mosaico", "dl")
    #9 /srv/www/example/my.example.org/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
    #10 /srv/www/example/my.example.org/index.php(21): menu_execute_active_handler()
    #11 {main}

Ideally Mosaico should be checking that the result of the same submission is not a failure - looks like CiviCRM returns HTTP 200 when this happens which may not be helping.

**Comment by petednz** [comment] 2016-09-07 22:12
Thanks for spotting that chris - so giving users "skip IDS check" drupal permission overcomes this but is perhaps the wrong solution? perhaps in short term it should be in documentation? but longterm is there a way to do this without reducing this protection?

**Comment by deepak-srivastava** [comment] 2016-09-13 09:32
@petednz @xurizaemon Thanks for catching it. We should definitely add some checks & report any failures. 
W.r.t skipping IDS, think rule should be same as any other backend forms in civi, to start with.

**Comment by deepak-srivastava** [comment] 2016-10-03 15:44
Update: new beta release can detect and report "save" failures.

**Comment by deepak-srivastava** [comment] 2016-10-04 20:39
Closing this ticket. Please re-open if still an issue with reporting errors. Thanks.

**Closed by deepak-srivastava** 2016-10-04 20:39 UTC
Labels: bug

**Comment by sunnycs121** [comment] 2018-11-01 16:25
Giving "skip IDS check" drupal permission does not solved this issue for me.

**Comment by xurizaemon** [comment] 2018-11-01 18:28
@sunnycs121 this issue is a couple of years closed.

If you are confident it's the same issue unfixed two years later, then you're posting in the right place, but I suggest you provide more complete details (eg version of CiviCRM, plugin etc and steps to reproduce).

Even just saying "repeated steps to reproduce per original description with current release 1.1.1.1" is informative, as it tells that the bug is still present and gives instructions.

If you're not confident it's the same issue for you, open a new issue with those same details. 

Plenty of resources on writing good or effective bug reports out there for you to educate yourself.

https://chat.CiviCRM.org is a good place to ask for help in doing this.

**Comment by sunnycs121** [comment] 2018-11-02 14:30
CiviCRM ver: 5.6.1
CMS: Drupal 7.59

CiviCRM was recently upgraded to 5.6.1 then problem started. It came out to be mailgun extension was installed which had its own IDS.php file, disabling extension solved the issue but as that was not a better solution, found out that in civi log files directory there is a file "Config.IDS.ini", in that file i added following exception and then enabled mailgun extension, all started to work.

exceptions[]        = json

Thanks!
