### ISSUE TITLE
I have upgraded to Mosaico 2.5 and CiviCRM 5.28.1 (on Wordpress 5.5), but my problem remains.

### ISSUE THREAD

**Issue by masetto** [veda-consulting/uk.co.vedaconsulting.mosaico#398] opened 2020-08-22 10:37 UTC
I have upgraded to Mosaico 2.5 and CiviCRM 5.28.1 (on Wordpress 5.5), but my problem remains. 
Below the screenshot:
![image](https://user-images.githubusercontent.com/9961202/90896433-eba7ec00-e3c3-11ea-9b78-98848bb091ca.png)

Note that `/mosaico/img/` after domain name does not exist. Maybe it depends on my configuration? But I can't figure out which one.
Any ideas?
Thank you

_Originally posted by @masetto in https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/issues/393#issuecomment-678293483_

**Comment by mattwire** [comment] 2020-08-22 13:19
Hi @masetto I think this is specific to your setup. Some early versions of mosaico had issues with paths. Did you try to start with a new template from versafix-1 - because if you are still using a template you created on an older version you may have problems.

**Comment by hughrun** [comment] 2020-08-24 01:03
I have exactly the same problem as @masetto as of today after upgrading. I have upgraded to latest WordPress (5.5) CiviCRM (5.28.3) and Mosaico (2.5.1597918155). I tried creating a new template from versafix-1 but this doesn't resolve the problem.

**Comment by bkaless** [comment] 2020-08-24 08:59
Hi, I had the same issue. I forgot php7.3-gd in my installation when I switched from PHP 7.2 to PHP 7.3. 
Adding this and restarting the webserver solved my issue.

**Comment by dandrzejewski** [comment] 2020-08-30 18:36
I am also having the same problem. If there are any log files or data I can capture, I'd be happy to oblige.

**Comment by eomapw** [comment] 2020-08-31 02:05
I have the same problem. I am using CiviCRM 5.25.0, WP 5.5 just upgraded Mosaico. I have tried using different templates but the problem persists.  I am not a developer/tech person but the muggins responsible for Civi because there is no-one else to do it. Would love more explanation of this:  "I forgot php7.3-gd in my installation when I switched from PHP 7.2 to PHP 7.3. Adding this and restarting the webserver solved my issue." Is this something my webhost should do? Help!

**Comment by hughrun** [comment] 2020-08-31 08:06
@eomapw it's a PHP extension ("Graphics Draw") so if you have supported hosting you'd need them to do it. However I think this is a red herring because nobody else has mentioned updating their PHP, and certainly that's not something that caused this issue on my install. I have both `gd` and `imagick` PHP extensions which should cover all possibilities, and haven't updated PHP for a while.

Futher info: this **seems to be related to one of the Civi updates between 5.27.4 and 5.28.3**. I've previously noticed issues after upgrades so I checked Mosaico after the CiviCRM update but before I updated either Mosaico or WordPress to the latest versions - this problem was apparent prior updating the latter two.

**Comment by mattwire** [comment] 2020-09-01 16:25
If you are having this problem on Wordpress after upgrading to Wordpress 5.5 and CiviCRM > 5.26 please can you try to "update your permalinks": Wordpress menu -> Settings -> Permalinks then click "Save changes".
Try to load your mosaico editor and see if the problem is gone!

**Comment by hughrun** [comment] 2020-09-01 22:49
Thanks for looking into it @mattwire . I've tried updating permalinks but unfortunately it doesn't fix it.

**Comment by mattwire** [comment] 2020-09-03 11:46
Please check your CiviCRM paths. In the case of @masetto the problem was that the wordpress base page was not working with clean URLs enabled.

Check your CiviCRM paths/resource URLs and make sure that you are not overriding them if you don't need to.

In CiviCRM make sure that "Wordpress Base Page" is setup as "civicrm" with no "/" - see https://github.com/civicrm/civicrm-core/pull/18332 so this will be fixed in 5.29.
 
In Wordpress make sure you have a CiviCRM base page (should be at https://yoursite.com/civicrm).
**Important:** Go to Settings -> Permalinks and click "Save Changes".

Now Mosaico images should work and navigating to https://yoursite.com/civicrm/mosaico/img should give a 200 OK and a blank page.

**Comment by hughrun** [comment] 2020-09-03 22:59
Boom! Thanks @mattwire that looks like it's fixed it - the trailing slash on the base page does seem to be the culprit.

**Comment by mlutfy** [comment] 2020-09-24 15:10
Can we close this issue? It also helped me debug issues with Mosaico under WordPress.

I would add:

* Make sure that the base page is a post_type "page"
* Make sure that the title of the base page is in lower-caps.

This was on an inherited site, where the CiviCRM had been deleted and later re-created, under a new post type.

We added a check to our internal [monitoring extension](https://lab.civicrm.org/extensions/symbiotic/-/blob/master/CRM/Symbiotic/Utils/Check/Wordpress.php). It checks for some symbiotic-specific things (such as the CIVICRM_CMSDIR constant, which is not normally required), but might help other folks trying to debug.

**Comment by mattwire** [comment] 2020-09-24 15:45
I think so - it would be nice to have a little bit on this in the mosaico docs though

**Closed as completed** 2020-10-09 19:18 UTC

**Comment by yorkshirerose** [comment] 2021-01-19 09:37
I realise this is a closed issue but I'm having the same issue. 

WordPress 5.6
CiviCRM 5.24.6 (I'm expecting to upgrade shortly)
Mosaico 2.5

I've checked the WordPress base page (no trailing slash), I've checked and saved the Permalinks, I've updated the title of the page in WP to lower case. There are custom resource URLs but these have not changed recently so I wasn't expecting this to be the cause.

@mattwire you mentioned clean URLs in WordPress - how do you usually implement this, or are you just referring to updating the permalinks?

Should I update CiviCRM, would that resolve the issue? We were planning to update the site shortly anyway but I don't know if that will actually fix this problem.

**Comment by kcristiano** [comment] 2021-01-19 12:51
@yorkshirerose  CiviCRM 5.24.6 won't work properly on WP 5.5+, so I believe that is the issue.

To support WP 5.5 (and subsequent versions) CiviCRM 5.26.x is required.  So I would start with that update.

**Comment by yorkshirerose** [comment] 2021-01-19 14:06
> 
> 
> @yorkshirerose CiviCRM 5.24.6 won't work properly on WP 5.5+, so I believe that is the issue.
> 
> To support WP 5.5 (and subsequent versions) CiviCRM 5.26.x is required. So I would start with that update.

@kcristiano Thank you! Just found out an overzealous member of staff clicked the update on WordPress, so that would explain why it broke just now. I will update CiviCRM and hopefully that will fix it.

**Comment by yorkshirerose** [comment] 2021-01-19 16:39
Just to confirm, the issue was that I was running an old version of CiviCRM and that updating has resolved the issue. Thanks to @kcristiano for pointing me in the right direction.
