### ISSUE TITLE
Icons in Mosaico not showing

### ISSUE THREAD

**Issue by RandyTobias** [veda-consulting/uk.co.vedaconsulting.mosaico#166] opened 2017-06-07 15:44 UTC
I'm not sure if this is a package issue or a web-server one, but icons don't load for me in Mosiaco. When trying to load various .ttf, woff, and woff2 files, I get 404s. I have a .htaccess file up in my extension directory that included:

<IfModule mod_mime.c>
    AddType application/vnd.ms-fontobject    .eot
    AddType application/x-font-opentype      .otf
    AddType image/svg+xml                    .svg
    AddType application/x-font-ttf           .ttf
    AddType application/font-woff            .woff
    AddType application/font-woff2           .woff2
</IfModule>

Alas, that doesn't seem to help. I do know my mime_module is loaded. This is a site that is running all https, but that doesn't seem to be the issue (not getting the mixed content warning). The thing that is most odd to me is that this is a Joomla site, and I know our template uses Font Awesome elsewhere, so not sure why it would load fine from some directories but not others.

**Comment by freedomlives** [comment] 2017-06-14 16:28
The Mosaico plugin is bundling its own font awesome library.  
..? (not sure what this part will be in Joomla)/civicrm/ext/uk.co.vedaconsulting.mosaico/packages/mosaico/dist/fa/fonts/

**Comment by RandyTobias** [comment] 2017-06-14 16:34
Right. My Joomla has its own font awesome libraries for the themes. However, my problem is that Mosaico is trying to load its own, which normally should be fine, but I'm getting server errors reporting that these files can not be loaded. It throws me off because I can load these files elsewhere.

**Comment by totten** [comment] 2017-12-01 04:59
Thanks for reporting, @RandyTobias!

At the risk of being pedantic, I just want to emphasize that the Joomla and Mosaico copies of FontAwesome are independent. It wouldn't matter if Joomla successfully loads the FontAwesome files in its pages-- Mosaico still needs to load its copy of FontAwesome in the Mosaico IFRAME. (Mosaico loads in an IFRAME, and then communicates with the main page via JS.)

You'd want to verify that there are files on disk under `uk.co.vedaconsulting.mosaico/packages/mosaico/dist/fa/fonts/`.

Taking a bit of a leap (based on a common problem)... this sounds like it could be [an installation issue](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/153#issuecomment-346915244). tldr: you'll get lots of 404's if you do a basic/improvised install process. Check the README for installation steps. (Note, though, that the exact 404 symptom has changed over time -- it's basically circumstantial depending on the revision of the codebase.)

In 2.0-beta3 (coming soon), we've added a check (#217) to provide a clearer, more proactive warning if that's the problem.

I'm inclined to close this (because 404's on static assets suggests an install problem), and there's mitigation for the install problem. However, since I never reproduced this exact symptom, I could be wrong. If the problem recurs in 2.0-beta3, then please reopen the issue!

**Closed as completed by totten** 2017-12-01 04:59 UTC
Labels: topic:hyperlinking
