### ISSUE TITLE
upgrade fails badly on two sites in two days

### ISSUE THREAD

**Issue by JoeMurray** [veda-consulting/uk.co.vedaconsulting.mosaico#304] opened 2019-05-01 15:29 UTC
There is a message in CiviCRM indicating people should upgrade to newer version of this extension. On a Drupal 8 site on Monday this seems to have failed by removing the files in the extension directory (though notably not a subdirectory) but not writing in the new ones. Similar thing happened on a Joomla site yesterday. Is there something non-standard about upgrading this extension?

FWIW, on the Drupal site the error manifested as

Warning

Error loading module file (/var/www/example.com/htdocs/sites/default/files/civicrm/ext/uk.co.vedaconsulting.mosaico/mosaico.php). Please restore the file or disable the module.

**Comment by mattwire** [comment] 2019-05-01 16:43
@JoeMurray So we finally marked it as stable and released 2.0 this week.  So it's the first time it has been available for automatic upgrade.  It is different in the sense that it is automatically packaged up and then downloaded from the custom link that is generated here: https://civicrm.org/extensions/mosaico-civicrm-integration/version-20
I'm not really familiar with how the extension downloader works and where it gets the path from but the package itself looks fine and you should be able to manually unzip it.  I presume it's not directory permissions or similar?

**Comment by monishdeb** [comment] 2019-05-01 18:15
@mattwire when I tried to `Download and upgrade` mosaico 2.0 it eventually ends with WSOD. And when I looked in the ext dir there were no files present it. It seems like something broke during the zip extract. It's certainly not a permission issue but then I have to manually unzip the package as the autoinstall was not working on other sites too.

**Comment by totten** [comment] 2019-05-01 18:32
> (*JoeMurray*) ... [the upgrade] failed by removing the files in the extension directory (though notably not a subdirectory) but not writing in the new ones.

> (*mattwire*) I presume it's not directory permissions or similar?

* *Permissions* - That was my first thought.
* Which version are you upgrading from? 1.x-stable or 2.0-betaX?
* Which folder did it fail to delete? Perhaps `packages/mosaico` or something else?

One theory... installing the 2.0-beta has always required some kind of unfamiliar steps (i.e. because normal web-GUI downloader didn't show the beta). Download [Option 1](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/#option-1-download-via-web) and [Option 2](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/#option-2-download-via-cli) should produce all files with similar permissions. However, option [Option 3](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/#option-3-download-via-git-preferred-for-development) and any other improvised path would have multiple/distinct download steps, which is an opportunity to produce different permissions on different subfolders.

> (*mattwire*) It is different in the sense that it is automatically packaged up and then downloaded from the custom link that is generated here: https://civicrm.org/extensions/mosaico-civicrm-integration/version-20

I don't think the extension's official build/distribution process is the issue:

* You can inspect the zipballs for 1.0, 2.0-betaX, and 2.0-final -- they're all pretty similar in structure. The zip contains one top-level folder. Underneath that, it has`mosaico.php`,  `packages`, ad nauseum.
* On my local, I tried running downloads using the built-in download system with various versions of Mosaico, and they all produced the expected directory structure with similar permissions. (Note: `cv dl` uses the same download+extract as the web GUI, but it supports alternate sources/feeds.)
    * `cv dl uk.co.vedaconsulting.mosaico@https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/archive/1.1.zip`
    * `cv dl uk.co.vedaconsulting.mosaico@https://storage.googleapis.com/civicrm/mosaico/2.0-beta4.1528762072/uk.co.vedaconsulting.mosaico-2.0-beta4.1528762072.zip`
    * `cv dl uk.co.vedaconsulting.mosaico@https://storage.googleapis.com/civicrm/mosaico/2.0.1556289017/uk.co.vedaconsulting.mosaico-2.0.1556289017.zip`
* _Full disclosure_: I did come across one oddity in the zip files. It looks like a red herring, but I'll mention it in case someone sees an angle I missed:
    * When I *manually* extract Mosaico 2.0-final on OSX with the cli command `unzip` (v6.00), then it produces very open file permissions (`777`).
    * I spot-checked other versions (1.1, 2.0-beta4) and other extensions (flexmailer, extendedreport), and everything gives the normal/expected permissions (`755`).
    * Also, if I switch to Civi/PHP extractor instead of running `unzip`, then it gives the normal `755`.
    * This oddity wouldn't explain an experience like Joe's -- because everything normally works with the tighter `755`, and his old version should have been written as `755`, which would be typical, and which typically allows upgrade.

**Comment by totten** [comment] 2019-05-01 18:36
Crossed wires with Monish's post. Thinking about these:

> (*monishdeb*) And when I looked in the ext dir there were no files present it. It seems like something broke during the zip extract. It's certainly not a permission issue but then I have to manually unzip the package as the autoinstall was not working on other sites too.
>
> (*totten*) I did come across one oddity in the zip files. ... it produces very open file permissions (777) ... [instead of] the normal/expected permissions (755).

Wild theory: Maybe some subtle change in `.zip` encoder or `.zip` format could manifest as different quirks when extracting with different versions/implementations of `unzip`?

**Comment by alexmarketaccess** [comment] 2019-05-01 18:55
I'm running civiCRM 5.12.4 under Joomla 3.9.5, and just went to update Mosaico using the automated update. It failed, with the notice:
You have requested a non-existent service: mosaico_graphics

Any suggestions?

**Comment by totten** [comment] 2019-05-01 19:04
Re: @alexmarketaccess 

> You have requested a non-existent service: mosaico_graphics

If you can find a stack trace (e.g. in the browser or in `CiviCRM.log.*`), then check to see if it mentions [mosaico_civicrm_check()](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/2.0/mosaico.php#L198). 

* If so, then I'd propose adding another `catch{}` block.
* If it doesn't... then, well, I guess we see what it says.

For a resolution, try clearing out `templates_c`.

**Comment by MegaphoneJon** [comment] 2019-05-01 19:24
I had an error similar to @alexmarketaccess (coming from a post-2.0b4 but pre-2.0 version) but I cleared caches and it went away so I moved on.

**Comment by alexmarketaccess** [comment] 2019-05-01 19:31
@totten 

I've cleared caches. Issue persisted. So I uninstalled both Mosaico and FlexMailer, and reinstalled both (FlexMailer I uploaded to /ext and installed), and Mosaico I installed directly from the Extensions->Add New in civicrm. 

No error, but now when I select Mailings->New Mailing, I see this (obviously not what one wants to see):

![capture](https://user-images.githubusercontent.com/15691820/57037786-1944b100-6c26-11e9-950d-a893fdf9be49.png)

**Comment by JoeMurray** [comment] 2019-05-01 19:34
Trying to help with debugging here...

Looking at the directory (which has since been overwritten, but I remember the colours displayed when I did ls -al) it was all 777 permissions, with the group owner being apache. The subdirectory that wasn't removed was indeed packages. I'm not sure why that one is different than the dozen other subdirs. It makes no sense that there could have been write problems. Maybe having a semi-empty directory might have prevented a successful unzip or whatever the autoinstaller uses?? This is CentOS Linux release 7.5.1804 (Core)

FWIW, in this D8 case with a site in production for 1 month, it's most likely that the original installation was done on a staging instance and the files deployed to production via git though it is possible there was a manual install on this instance.

The other instance was Ubuntu 16.04. I didn't look at the server before or during the problem so I can't help with file permissions. But it is a very different OS and CMS so this provides evidence the problem is somewhere in the installer moving from prior manual installation to an auto-install of an upgrade.

**Comment by mattwire** [comment] 2019-05-01 20:02
@alexmarketaccess On your first point about mosaico_graphics - I've seen that on older versions and core upgrades.  It's nothing to worry about if you do see it as clearing caches always resolves it.  Looking at your screenshot I'd say either browser or civi caches have not fully cleared.

**Comment by totten** [comment] 2019-05-01 20:08
> (totten) I did come across one oddity in the zip files. ... it produces very open file permissions (777) ... [instead of] the normal/expected permissions (755).

Replying to myself - this seems to involve the version of PHP used  when building the zip. It's fine on PHP 5.4 (MAMP) but weird on PHP 5.6 (MAMP or nix). Since this smells like a different/distinct issue, I've split it off as #305.

**Comment by alexmarketaccess** [comment] 2019-05-01 20:11
I've cleared caches (both via civiCRM and on file system directly), and then tried a couple of web browsers just in case, and still the same issue. Also tried PHP 7.1 and 7.2 (default is 7.2) -- same issue in both cases.

**Comment by jitendrapurohit** [comment] 2019-05-16 03:03
We got the same issue after upgrading to version 2.0.

>You have requested a non-existent service: mosaico_graphics

cleared templates_c folder and it was fixed, but we still saw mosaico_graphics warning on system status page.

![image](https://user-images.githubusercontent.com/5929648/57823459-3e542a80-77b5-11e9-8a96-a408c343331a.png)

Done menu rebuild and it was fixed too.

**Comment by khorporative** [comment] 2019-07-21 14:12
I just installed **Mosaico** from **CiviCRM Extensions** on CiviCRM 5.13.5 on Drupal 7.x

Same error
![image](https://user-images.githubusercontent.com/18428628/61592323-7d9a5f80-abda-11e9-8b62-5910c8a8f2db.png)

Running **Cleanup Caches and Update Paths** from **Administer > System Settings** menu did not help.

**Comment by mlutfy** [comment] 2019-07-31 22:00
I ran into issues with 'mosaico_graphics' where the error happens even if I did not run an upgrade. Might be caused from a cache-flush from the hosting system.

If anyone runs into this, try manually setting `cv api Setting.create mosaico_graphics=auto` and see if it fixes the issue. I'm waiting to see when the issue happens again, but I suspect  `Civi::settings()->get('mosaico_graphics')` returns null instead of the default value (auto) because there was a cache flush while extensions were not loaded.

This can happen if the cache was flushed during an upgrade pre-[PR13551](https://github.com/civicrm/civicrm-core/pull/13551), but that has been fixed for a few months now (i.e. a few CiviCRM versions ago), so I'm not sure what could cause the issue to persist.

**Comment by mattwire** [comment] 2019-10-11 09:26
No reports of this recently. I think this could have been caused by upgrading from multiple versions of Mosaico as we didn't have a stable release - but going forward we do.

**Closed as completed by mattwire** 2019-10-11 09:26 UTC

**Comment by petednz** [comment] 2020-08-20 23:23
i just hit this once post the 5.28.1 upgrade. shrug. needed to mention it somewhere. agree it seems related to caching. using the link got me the page the second time, but going to system status gave me the error more than once. i cleared civi caches and next time i tried i got the system status page to load.
